name: conversational-agent

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $pgql_db
      POSTGRES_USER: $pgql_user
      POSTGRES_PASSWORD: $pgql_psw
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  qdrant:
    image: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant/storage:/qdrant/storage 

volumes:
  pgdata:
